import "./globals.css";
import { ReactNode } from "react";
import { Noto_Sans } from "next/font/google";
import type { Metadata } from "next";
import EmotionCacheProvider from "@/providers/EmotionProvider";
import GlobalHeader from "./_components/GlobalHeader/GlobalHeader";
import GlobalFooter from "./_components/GlobalFooter/GlobalFooter";

const NotoSans = Noto_Sans({
	variable: "--font-noto-sans",
	display: "swap",
	weight: "400",
	style: ["normal"],
	subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
	title: "Next Build Guide",
	// description: "Generated by create next app",
	// keywords: [],
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
	return (
		<html lang="ru">
			<body className={NotoSans.variable}>
				<EmotionCacheProvider>
					<GlobalHeader />
					{children}
					<GlobalFooter />
				</EmotionCacheProvider>
			</body>
		</html>
	);
};

export default RootLayout;
